target: a_quitte_l_entreprise

drop_columns:
  - Unnamed: 0
  - id_employee
  - eval_number
  - code_sondage

feature_sets:
  raw_baseline:
    num:
      - age
      - revenu_mensuel
      - annee_experience_totale
      - annees_dans_l_entreprise
      - annees_dans_le_poste_actuel
      - annees_depuis_la_derniere_promotion
      - distance_domicile_travail
      - satisfaction_employee_environnement
      - satisfaction_employee_equipe
      - satisfaction_employee_equilibre_pro_perso
      - satisfaction_global
      - note_evaluation_precedente
      - note_evaluation_actuelle
      - niveau_hierarchique_poste
    cat:
      - genre
      - statut_marital
      - departement
      - poste
      - niveau_education
      - domaine_etude
      - frequence_deplacement

  fe_compact:
    num:
      - age
      - revenu_mensuel
      - annee_experience_totale
      - annees_dans_l_entreprise
      - annees_dans_le_poste_actuel
      - annees_depuis_la_derniere_promotion
      - distance_domicile_travail
      - satisfaction_global
      - note_evaluation_precedente
      - note_evaluation_actuelle
      - niveau_hierarchique_poste
      - salary_vs_level
      - experience_mismatch
      - promotion_speed
      - promotion_delay
      - delta_evaluation
      - is_low_salary_for_job
      - stagnation_flag
      - long_commute
      - mid_level
      - career_frustration
      - fn_risk_profile
    cat:
      - statut_marital
      - departement
      - poste
      - niveau_education
      - domaine_etude
      - frequence_deplacement
      - age_bucket
      - revenu_bin

  fe_fn_focus:
    num:
      - age
      - revenu_mensuel
      - annees_dans_l_entreprise
      - annees_dans_le_poste_actuel
      - distance_domicile_travail
      - satisfaction_global
      - niveau_hierarchique_poste
      - salary_vs_level
      - experience_mismatch
      - promotion_speed
      - delta_evaluation
      - is_low_salary_for_job
      - stagnation_flag
      - career_frustration
      - grey_zone_employee
      - fn_risk_profile
      - consulting_risk
      - married_fn_risk
      - tech_fn_risk
      - travel_fn_risk
      - categorical_fn_profile
      - senior_frustration
      - tech_stagnation
      - consulting_travel_risk
    cat:
      - statut_marital
      - departement
      - poste
      - domaine_etude
      - frequence_deplacement
      - age_bucket
      - revenu_bin
